### ISSUE TITLE
A little bit more documentation on where to change sizing options and how to ignore certain types of zeds.

### ISSUE THREAD

**Issue by GitSugar** [trub64/trubs-variants#2]
Basically the title. 
It would be nice to know how do I have to put entities in the "ignore_entity_list":{} part of the config for it to ignore said entity. I have tried "","" and ["",""] even "1": "", "2":"" and nothing seems to work.

**Comment by trub64** [comment]
It is sort of misnamed, as it's a dict and not a list.  each entry would be the entity name (like "zombieArleneFeral") and a string reason why it should be ignored.  Each set is separated by a comma, with a colon between the key and the value:

"ignore_entity_list":{
    "thisZombie": "just cuz", 
    "thatZombie":"they suck"
}

**Comment by trub64** [comment]
As a Note, this mod is idled right now, but I'll see what I can do to add more documentation, but the config file just needs to correspond to JSON format.

**Comment by GitSugar** [comment]
I'll close this issue now. 
Thank you very much!
